runtime:
  cache_dir: ./.cache/antora

site:
  title: OpenShift Starter Guides
  url: http://rampadc.github.io/openshift-starter-guides-carbon/
  start_page: rhs-openshift-starter-guides::index.adoc

content:
  sources:
    - url: git@github.com:redhat-scholars/openshift-starter-guides.git
      tags: []
      branches: [ocp-4.7, ocp-4.8, ocp-4.9]
      start_path: documentation

asciidoc:
  attributes:
    experimental: true
    parksmap-version: latest
    parksmap-image: quay.io/openshiftroadshow/parksmap
    openshift-docs-url: https://docs.openshift.com/container-platform/4.9
    openshift-version: 4.9
    project-namespace: workshop
    release-version: roks
    roks-login-url: https://cloud.ibm.com/authorize/devcluster
    page-pagination: true
    lab: java
    lab-name: Java
  extensions:
    - ./lib/tab-block.js
    - ./lib/remote-include-processor.js

ui:
  bundle:
    url: https://github.com/rampadc/antora-x-carbon/releases/download/main-61cdb47/ui-bundle.zip
    snapshot: true
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
    - path: .nojekyll
    
output:
  dir: ./gh-pages

antora:
  extensions:
    - '@antora/lunr-extension'